# fly.toml app configuration file for unified-backend
app = 'unified-backend'
primary_region = 'nrt'

[build]

[processes]
  web = "/app/.venv/bin/gunicorn -w 1 -k uvicorn.workers.UvicornWorker --keep-alive 120 --timeout 180 --bind 0.0.0.0:8000 main:app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "15s"
    timeout = "30s"
    grace_period = "300s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1